#language: c

sudo: required
dist: bionic

notifications:
  email: false

before_script:
  - sudo apt-get update
  - python3 --version
  - python2 --version
  - "sudo apt-get install -qq python3-pip python-tk scons git cmake || true"
  - "sudo pip3 install setuptools || true"
  - "sudo pip3 install tensorflow keras keras2onnx onnxruntime || true"
  - "sudo apt-get install -qq libboost-dev pybind11-dev || true"

script:
  - git clone https://github.com/google/googletest.git
  - mkdir -p googletest/build && cd googletest/build && cmake .. && make && sudo make install
  - cd ../..
  - mkdir -p gtest/models
  - wget https://github.com/lwnn/lwnn/releases/download/v0.1/mnist.h5 -O gtest/models/mnist.h5
  - scons
  - ./lwnn_gtest

env:
  - DISABLE_OPENCL=True

